### ISSUE TITLE
bot sends invalid jpg in message when tapmusic fails to deliver lastfm chart

### ISSUE THREAD

**Issue by rosecoloredcode** [kr-ish/bababot#4]
example:

![image](https://user-images.githubusercontent.com/91800837/140668234-ba4a3efc-9b8f-4e92-9540-ce34b0af5005.png)

the tapmusic website returns the following when this happens.

> <b>Error 99 - </b><i>ws.audioscrobbler.com: Service not available (404 Not Found)</i> 

something like the following might work to replace the output of `fm_chart()` but i'm too lazy to test it myself rn for a full PR

`if len(BytesIO.getvalue(image))<1000:`
`    await ctx.reply(f'chart not found! lastfm username "{fm_username}" may be invalid')`
`else:`
`    await ctx.send(file=discord.File(image, filename=f'{fm_username}_{duration}.jpg'))`

**Comment by kr-ish** [comment]
ty @rosecoloredcode 🙌
